name: "Build, release and publish"

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  test:
    name: Test
    uses: ./.github/workflows/action-test.yml
    with:
      python-version: "3.8"
      environment: "cloud"
    secrets:
      NOCO_URL: ${{ secrets.NOCO_URL }}
      NOCO_API_KEY: ${{ secrets.NOCO_API_KEY }}
      NOCO_BASE_ID: ${{ secrets.NOCO_BASE_ID }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine pytest flake8
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
      
      # Step 7: 发布到 PyPI
      - name: Publish to PyPI
        if: github.ref_type == 'tag'  # 仅当触发事件是标签时执行
        env:
          TWINE_USERNAME: __token__  # 固定用户名，表示使用 API Token
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m twine upload dist/*


